config/routes.rb
Rails.application.routes.draw do

  root                     								        'static_pages#welcome'
  get		'/what-have-you-done'					         => 'static_pages#projects'
  get		'/game-of-life'							           => 'static_pages#game_of_life'
  get		'/has-matheus-portela-failed-already'  =>	'static_pages#has_matheus_portela_failed'
  get   '/who-are-you'							           =>	'static_pages#about_me'
  get   '/quaternions'                         => 'static_pages#quaternions'
  get   '/jlpt'                                => 'static_pages#jlpt'
  get   '/jlpt/vocabulary'                     => 'static_pages#jlpt_vocabulary'
  get   '/jlpt/vocabulary/sample'              => 'static_pages#jlpt_vocabulary_get'
  get   '/jlpt/grammar'                     => 'static_pages#jlpt_grammar'
  get   '/jlpt/grammar/sample'              => 'static_pages#jlpt_grammar_get'
  get   '/jlpt/kanji'                     => 'static_pages#jlpt_kanji'
  get   '/jlpt/kanji/sample'              => 'static_pages#jlpt_kanji_get'
  get   '/blog'	 								               =>	'posts#index'
  get   '/signup'  								             =>	'users#new'
  get   '/login'   								             =>	'sessions#new'
  post  '/login'   								             =>	'sessions#create'
  get   '/logout'  								             =>	'sessions#destroy'
  
  resources :posts, :path => 'blog' do
    resources :comments
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
    per_page = 10

	validates_presence_of :title
	validates_presence_of :body

    def timestamp
        created_at.strftime('%d %B %Y %H:%M:%S')
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(page: params[:page], per_page: 15).order('created_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find_by_id(params[:id])
  end

  # GET /posts/new
  def new
    if logged_in?
      @post = Post.new
    else
      redirect_to login_path
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <!-- Actual form -->
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div>
  <h2><%= link_to post.title, post_path(post) %></h2>

  <small><em><%= post.timestamp %></em></small>

  <p><%= truncate(strip_tags(post.body), length: 600) %></p>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <%= stylesheet_link_tag "css/main.css", "css/blog.css" %>
  <title>Blog | levy's sandbox</title>
</head>

<body>
  <%= javascript_include_tag "application" %>

  <div class='header'><%= render "layouts/header" %></div>

    <p id="back-top">
    <a href="#top"><span></span></a>
    <p>

    <div class='wrapper'>
    <div class="welcome">
      <% if logged_in? %>
        <p id="new-post">
          <a href='new'><span></span>novo post</a>
        </p>
      <% end %>
    </div>

    <header class="post-header">
      <h1 class="post-title">blog</h1>
    </header>

    <div class="wrapper">
      <div class="posts-index" id="posts-index">
        <%= render @posts %>
      </div>

      <% if @posts.next_page %>
        <div id="infinite-scrolling">
          <%= will_paginate %>
        </div>
      <% end %>
    </div>
</body>

<body>
<footer><%= render "layouts/footer" %></footer>

</html>

app/views/posts/index.js.erb
var delimiter = $('<div class="page-delimiter" data-page="<%= params[:page] %>"></div>');
$('#posts-index').append(delimiter);
$('#posts-index').append('<%= j render @posts %>');
$('.pagination').replaceWith('<%= j will_paginate @posts %>');
preparePagination(delimiter);
<% unless @posts.next_page %>
$('#infinite-scrolling .pagination').remove();
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <%= stylesheet_link_tag "css/main.css", "css/posts.css", "css/comments.css" %>
  <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
  <title><%= @post.title %></title>
</head>

<body>
  <%= javascript_include_tag "application" %>

  <div class='header'><%= render "layouts/header" %></div>

  <p id="back-top">
    <a href="#top"><span></span></a>
  <p>
  
  <div class='wrapper'>
    <header class="post-header">
      <h1 class="post-title"><%= @post.title %></h1>
    </header>
    <div class="post-content">
    <%= @post.body.html_safe %>
    <br>
    <br>
    <hr>

    <h3>comments</h3>
    <div id="comments">
        <%= render :partial => @post.comments.reverse %>
    </div>

    <hr>
    <br>

    <%= form_for([@post, Comment.new], remote: true) do |f| %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :comment %>
        <%= f.text_area :body, size: '60x12' %>
      </div>
      <div class="field">
        <%= f.submit %>
      </div>
    <% end %>

    <br><br>
    <% if logged_in? %>
    <%= link_to 'Edit', edit_post_path(@post) %> |
    <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %> |
    <% end %>
    <%= link_to 'Back', posts_path %>
</body>

<footer><%= render "layouts/footer" %></footer>

</html>